spring:
  application:
    name: product-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/product
    url: jdbc:mysql://localhost:3307/giakor
    username: giakor
    password: giakor


#    username: product_user
#    password: StrongAppPassword123!


  jpa:

    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8081
