spring:
  application:
    name: product-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/product
    url: jdbc:postgresql://ep-silent-sunset-aboi2v9d-pooler.eu-west-2.aws.neon.tech/product?sslmode=require&channel_binding=require'
    username: neondb_owner
    password: npg_R9Ibx3kKhPTM
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8081
