spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
#    url: jdbc:mysql://localhost:3307/giakor
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  #    username: product_user
#    password: StrongAppPassword123!


  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true


#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  message: "Hello Product!"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size:  5MB
      max-history:  7
