spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ecom_user
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: giakor
#    password: giakor
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create


server:
  port: 8082


management:
  endpoints:
    web:
      exposure:
        include: "*"


app:
  message: "Hello User!"